# Generated by Django 4.0.6 on 2022-08-02 21:40
import os

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


def create_default_link_objects(*_) -> None:
    DIR_LINK_ICONS = os.path.join(settings.MEDIA_ROOT, "images/links/")

    for order, filename in enumerate(os.listdir(DIR_LINK_ICONS)):
        filepath = os.path.join(DIR_LINK_ICONS, filename)

        if os.path.isfile(filepath):
            link = home.models.Link(
                name=filename.split(".")[0],
                url="https://example.com/",
                icon=f"images/links/{filename}",
                order=order
            )
            link.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('icon', models.FileField(help_text='Only SVG files. The image will be used to show links on home page', upload_to='images/links/', validators=[home.models.validate_svg_file])),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=256)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField(verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='home.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/posts')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='home.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(create_default_link_objects)
    ]
