# Generated by Django 4.0.6 on 2022-07-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='description',
        ),
    ]
