# Generated by Django 4.0.6 on 2022-07-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_comment_post_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkOnPost',
            new_name='PostLink',
        ),
    ]
