# Generated by Django 4.0.6 on 2022-07-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_linkonpost_postlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='home.post'),
        ),
    ]
